---
# Source: fake-gpu/templates/configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: release-name-configmap
data:
  fake-gpu.yaml: |-
      nvidia:
      - name: NVIDIA Tesla T4
        uuid: GPU-abc
        driver_version: 540.33.01
        brand: Tesla
        cuda_version: 12020
        cuda_cores: 2560
        vbios_version: 90.04.1F.00.01
        image_version: 1.2
        serial: 0320119123456
        power:
          minLimit: 200000
          maxLimit: 850000
          defaultLimit: 450000
          enforcedLimit: 450000
          usage: 250000
        utilization:
          gpu: 15
          memory: 15
        memory:
          total: 16160000000
          free: 16160000000
        pci:
          bus_id: 0000:00:1E.0
          device_id: 1234
          domain_id: 0
          sub_system_id: 5678
        nvlink:
          version: 1.0
          capacity: 1
          bandwidth: 25
          peer_gpu:
          - GPU-bcd
        mig:
          enabled: false
        events:
        - eventType: 8
          eventData: 43
        - eventType: 8
          eventData: 45
        dcgm:
          fields:
          - fieldId: 147 #Field Identifiers.
            fieldName: NVML_FI_DEV_NVSWITCH_CONNECTED_LINK_COUNT
            fieldType: unsigned int # Field Types. [double, unsigned int, unsigned long, unsigned long long, signed long long].
            fieldValue: 30
          - fieldId: 82
            fieldName: NVML_FI_DEV_MEMORY_TEMP
            fieldType: unsigned int
            fieldValue: 250
          - fieldId: 83
            fieldName: NVML_FI_DEV_TOTAL_ENERGY_CONSUMPTION
            fieldType: unsigned int
            fieldValue: 0
          - fieldId: 139
            fieldName: NVML_FI_DEV_NVLINK_THROUGHPUT_DATA_RX
            fieldType: unsigned int
            fieldValue: 0
          - fieldId: 138
            fieldName: NVML_FI_DEV_NVLINK_THROUGHPUT_DATA_TX
            fieldType: unsigned int
            fieldValue: 0
          - fieldId: 142
            fieldName: NVML_FI_DEV_NVLINK_THROUGHPUT_RAW_RX
            fieldType: unsigned int
            fieldValue: 0
          - fieldId: 143
            fieldName: NVML_FI_DEV_REMAPPED_UNC
            fieldType: unsigned int
            fieldValue: 0
          - fieldId: 145
            fieldName: NVML_FI_DEV_REMAPPED_FAILURE
            fieldType: unsigned int
            fieldValue: 0
      - name: NVIDIA Tesla P4
        uuid: GPU-bcd
        driver_version: 440.33.01
        brand: Tesla
        cuda_version: 12020
        cuda_cores: 2560
        vbios_version: 90.04.1F.00.02
        image_version: 1.2
        serial: 12567890ABCDEF
        power:
          minLimit: 200000
          maxLimit: 850000
          defaultLimit: 450000
          enforcedLimit: 450000
          usage: 250000
        utilization:
          gpu: 10
          memory: 10
        memory:
          total: 16160000000
          free: 16160000000
        pci:
          bus_id: 0000:00:1E.1
          device_id: 1234
          domain_id: 0
          sub_system_id: 5678
        nvlink:
          version: 1.0
          capacity: 1
          bandwidth: 25
          peer_gpu: 
          - GPU-abc
        mig:
          enabled: false
        events:
        - eventType: 8
          eventData: 43
        - eventType: 8
          eventData: 31
        dcgm:
          fields:
          - fieldId: 147 #Field Identifiers.
            fieldName: NVML_FI_DEV_NVSWITCH_CONNECTED_LINK_COUNT
            fieldType: unsigned int # Field Types. [double, unsigned int, unsigned long, unsigned long long, signed long long].
            fieldValue: 30
          - fieldId: 82
            fieldName: NVML_FI_DEV_MEMORY_TEMP
            fieldType: unsigned int
            fieldValue: 250
          - fieldId: 83
            fieldName: NVML_FI_DEV_TOTAL_ENERGY_CONSUMPTION
            fieldType: unsigned int
            fieldValue: 0
          - fieldId: 139
            fieldName: NVML_FI_DEV_NVLINK_THROUGHPUT_DATA_RX
            fieldType: unsigned int
            fieldValue: 0
          - fieldId: 138
            fieldName: NVML_FI_DEV_NVLINK_THROUGHPUT_DATA_TX
            fieldType: unsigned int
            fieldValue: 0
          - fieldId: 142
            fieldName: NVML_FI_DEV_NVLINK_THROUGHPUT_RAW_RX
            fieldType: unsigned int
            fieldValue: 0
          - fieldId: 143
            fieldName: NVML_FI_DEV_REMAPPED_UNC
            fieldType: unsigned int
            fieldValue: 0
          - fieldId: 145
            fieldName: NVML_FI_DEV_REMAPPED_FAILURE
            fieldType: unsigned int
            fieldValue: 0
---
# Source: fake-gpu/templates/daemonset.yaml
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: release-name-fake-gpu
  labels:
    helm.sh/chart: fake-gpu-0.1.0
    app.kubernetes.io/name: fake-gpu
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/version: "1.16.0"
    app.kubernetes.io/managed-by: Helm
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: fake-gpu
      app.kubernetes.io/instance: release-name
  template:
    metadata:
      labels:
        helm.sh/chart: fake-gpu-0.1.0
        app.kubernetes.io/name: fake-gpu
        app.kubernetes.io/instance: release-name
        app.kubernetes.io/version: "1.16.0"
        app.kubernetes.io/managed-by: Helm
    spec:
      serviceAccountName: default
      securityContext:
        {}
      nodeSelector:
        kubernetes.io/os: "linux"
      containers:
        - name: fake-gpu
          env:
          - name: NODE_NAME
            valueFrom:
              fieldRef:
                fieldPath: spec.nodeName
          command:
            - /fake-gpu/entrypoint.sh
            - -idx
            - "87"
            - -name
            - fake-gpu
            - -source-path
            - /usr/local/fake-gpu
          securityContext:
            privileged: true
          image: "ghcr.io/chaunceyjiang/fake-gpu:v0.0.32"
          imagePullPolicy: IfNotPresent
          resources:
            limits:
              cpu: 250m
              memory: 150Mi
            requests:
              cpu: 20m
              memory: 20Mi
          volumeMounts:
          - name: nrisockets
            mountPath: /var/run/nri
          - name: host-dev
            mountPath: /host-dev
          - name: config
            mountPath: /etc/fake-gpu
          - name: config-file
            mountPath: /fake-gpu/fake-gpu.yaml
            subPath: fake-gpu.yaml
      volumes:
      - name: host-dev
        hostPath:
          path: /dev
          type: Directory
      - name: config
        hostPath:
          path: /usr/local/fake-gpu
          type: DirectoryOrCreate
      - name: nrisockets
        hostPath:
          path: /var/run/nri
          type: DirectoryOrCreate
      - name: config-file
        configMap:
          name: release-name-configmap
